import { createClient } from '@insforge/sdk';

const insforgeUrl = 'https://74mncgr7.us-east.insforge.app';
const insforgeAnonKey = 'anon_bef499c78be106f01604cd18d131443ba7118560b896ece1c8050f3e15f52a42';
const insforgeClient = createClient({ baseUrl: insforgeUrl, anonKey: insforgeAnonKey });

async function main() {
  const { data } = insforgeClient.storage.from('payment_qr').getPublicUrl('6318942962225713354_120.jpg');
  console.log('Public URL generated by SDK:', data.publicUrl);
}

main().catch(console.error);
